<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Version>2.5.0</Version>
    <AssemblyVersion>2.5.0.0</AssemblyVersion>
    <FileVersion>2.5.0.0</FileVersion>
    <InformationalVersion>2.5.0-corehost-2.6.3-network-read</InformationalVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
</Project>
